In [4]:
import numpy as np
import numpy.typing as npt

In [2]:
def real_f(x):
    return np.log(x+1)*np.sin(x)

In [3]:
x = [0., 0.63, 1.25, 1.88, 2.5]
y = [real_f(x) for x in x]

n+1 - количество точек  
n - количество участков  
  
Уравнения:  
2n = Для каждого участка (n участков) по 2 уравнения (начало и конец)  
2(n-1) = Для кажой из точек между участками (n-1) по 2 уравнения (для 1 и 2 производной)  
2 = Для граничных точек

In [17]:
def poly(x: np.float64, x_i: np.float64, der: int = 0, deg: int = 3) -> npt.NDArray[np.float64]:
    """Нахождение der производной полинома deg степени

    Args:
        x (np.float64): _description_
        x_i (np.float64): _description_
        der (int, optional): _description_. Defaults to 0.
        deg (int, optional): _description_. Defaults to 3.

    Raises:
        ValueError: _description_

    Returns:
        npt.NDArray[np.float64]: _description_
    """
    if der < 0: raise ValueError
    if deg < 0: raise ValueError
    return np.array([(x-x_i)**(deg_i-der) if deg_i >= der else 0 for deg_i in range(deg, -1, -1)])

In [18]:
for der in (0, 1, 2):
    for x_i in x[:-1]:
        print(poly(3, x_i, der, 3))

[27.  9.  3.  1.]
[13.312053  5.6169    2.37      1.      ]
[5.359375 3.0625   1.75     1.      ]
[1.404928 1.2544   1.12     1.      ]
[9. 3. 1. 0.]
[5.6169 2.37   1.     0.    ]
[3.0625 1.75   1.     0.    ]
[1.2544 1.12   1.     0.    ]
[3. 1. 0. 0.]
[2.37 1.   0.   0.  ]
[1.75 1.   0.   0.  ]
[1.12 1.   0.   0.  ]
